"""``llm-patch init`` — interactive scaffold for ``.llm-patch.toml``.

Writes a minimal project config so that subsequent commands (``compile``,
``chat``, ``push``) can pick up sensible defaults. No heavy imports —
this command is pure stdlib + click.
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

_TEMPLATE = """\
# llm-patch project configuration
# Generated by `llm-patch init`. Edit freely.

[project]
name = "{name}"
description = "{description}"

[compile]
# Folder of source documents to ingest.
source = "{source}"
# Where compiled adapters are written.
output = "{output}"

[runtime]
# Default base model used by `llm-patch chat`.
base_model = "{base_model}"

# [registry]
# Uncomment and set to a `module:factory` string to enable `push`/`pull`.
# Equivalent to: $env:LLM_PATCH_PLUGIN_REGISTRY = "my_pkg:build_registry"
# plugin = "my_pkg:build_registry"
"""


def _prompt(label: str, default: str, *, non_interactive: bool) -> str:
    if non_interactive:
        return default
    return click.prompt(label, default=default, show_default=True)


@click.command("init")
@click.option(
    "--path",
    "config_path",
    type=click.Path(dir_okay=False, path_type=Path),
    default=Path(".llm-patch.toml"),
    show_default=True,
    help="Where to write the config file.",
)
@click.option("--name", default=None, help="Project name (default: current folder name).")
@click.option("--source", "source_dir", default="./docs", show_default=True, help="Source documents directory.")
@click.option("--output", "output_dir", default="./adapters", show_default=True, help="Output adapter directory.")
@click.option("--base-model", default="google/gemma-2-2b-it", show_default=True, help="Default base model for `chat`.")
@click.option("--non-interactive", is_flag=True, help="Skip prompts; use flag values verbatim.")
@click.option("--force", is_flag=True, help="Overwrite an existing config file.")
def init(
    config_path: Path,
    name: str | None,
    source_dir: str,
    output_dir: str,
    base_model: str,
    non_interactive: bool,
    force: bool,
) -> None:
    """Initialize a project with a minimal ``.llm-patch.toml``."""
    if config_path.exists() and not force:
        click.echo(f"Refusing to overwrite {config_path} (pass --force).", err=True)
        sys.exit(1)

    default_name = name or Path.cwd().name
    project_name = _prompt("Project name", default_name, non_interactive=non_interactive)
    description = _prompt(
        "Description", "An llm-patch project.", non_interactive=non_interactive
    )
    src = _prompt("Source documents folder", source_dir, non_interactive=non_interactive)
    out = _prompt("Output adapter folder", output_dir, non_interactive=non_interactive)
    base = _prompt("Default base model", base_model, non_interactive=non_interactive)

    rendered = _TEMPLATE.format(
        name=project_name,
        description=description,
        source=src,
        output=out,
        base_model=base,
    )
    config_path.write_text(rendered, encoding="utf-8")
    click.echo(f"Wrote {config_path}.")
    click.echo("Next: `llm-patch doctor` to verify the environment, then `llm-patch compile`.")


__all__ = ["init"]
